name: build_and_test
on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        container: ["cimg/go:1.14", "cimg/go:1.15"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    env:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - name: Setup required permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: restore cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-mod
        with:
          path: /home/circleci/go/pkg/mod
          key: go-pkg-mod-{{ checksum "go.sum" }}
      - name: Precommit and Coverage Report
        run: |
          make ci
          mkdir $TEST_RESULTS/
          find . -name 'coverage.html' > "${TEST_RESULTS}/coverage.lst"
          tar -n -cf - -T "${TEST_RESULTS}/coverage.lst" | tar -C "${TEST_RESULTS}" -xvf -
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
      - name: store test output
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-contrib-test-output
            path: /tmp/test-results
  integration:
    strategy:
      matrix:
        target: [test-gocql, test-mongo-driver, test-gomemcache]
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: mkdir -p $TEST_RESULTS
      - name: Integration test ${{ matrix.target }}
        run: |
          make ${{ matrix.target }}
          find . -name 'coverage.html' > "${TEST_RESULTS}/coverage.lst"
          tar -n -cf - -T "${TEST_RESULTS}/coverage.lst" | tar -C "${TEST_RESULTS}" -xvf -
      - name: store test output
        uses: actions/upload-artifact@v2
        with:
            name: opentelemetry-go-contrib-test-output
            path: /tmp/test-results
